### ISSUE TITLE
body reader cannot be resumed after some timeouts 

### ISSUE THREAD

**Issue by james-callahan** [ledgetech/lua-resty-http#158]
e.g. when reading the chunk header times out here: https://github.com/pintsized/lua-resty-http/blob/e5deba5bde1db31adc7aad574bae5e89f83fd973/lib/resty/http.lua#L385-L391
Then trying to proceed results in the `tonumber` erroring

I think the solution is to have:
```lua
local str repeat -- Receive the chunk size 
  local err
  str, err = sock:receive("*l") 
  if not str then 
    co_yield(nil, err) 
  end 
until str
```

Similar fixes are likely required in other places.

**Comment by bfcx** [comment]
I met the same problem too

**Comment by pintsized** [comment]
Sorry for insanely slow reply. This isn't really a "problem", since the coroutine will have yielded `nil, err`. This is your signal that something has gone wrong (in this case, sounds like your timeout is too short) and you should abandon the connection. Resuming a coroutine which has yielded `nil, error` is, as you say, going to cause all kinds of problems.
