### ISSUE TITLE
about coroutine use in body_reader()

### ISSUE THREAD

**Issue by tweyseo** [ledgetech/lua-resty-http#179]
i can't understand the purpose of using `coroutine` to wrap the `body_reader()`.

**Comment by tweyseo** [comment]
after reading your code several times, i understand the purpose: leave the scope of  the local variables that created in 'reader' function at this 'reader' function, and every invoking of  this 'reader' function will restore to it's context where it `yield()`. when the invoking end, the local variables will be GC, and does not pollute the context outside. right?

**Comment by pintsized** [comment]
Hi, sorry for taking so long to reply.

Lua coroutines are used here simply because they fit the pattern well. The user may wish to read the body using an arbitrary chunk size (so as to manage their own streaming), but we are not in control of how the data arrives on the wire. So the body_reader coroutines can read from the wire, and yield when they have what the caller asked for. When the caller wants more, the coroutine is resumed from where it left off.

Using this mechanism you can chain coroutines as filters to one another, which happens a lot in [ledge](https://github.com/ledgetech/ledge) for example.

There is a performance cost associated with using coroutines in OpenResty, which is worth knowing about (they are implemented as a special case, with an allocation overhead). It would be possible to rewrite this module to just use functions and some state variables instead, which in theory would perform better. But in all the cases I've tested, you always end up i/o bound before anything else, and so this small allocation overhead seems worth it since the code is much easier to reason about than it would be otherwise, IMO.
