### ISSUE TITLE
https proxy support

### ISSUE THREAD

**Issue by leopeng1995** [ledgetech/lua-resty-http#193]
I see these comments in the code:

> Check that the scheme is http (https is not supported for connections between the client and the proxy)

So why is the reason lua-resty-http doesn't support this feature?

**Comment by pintsized** [comment]
AFAIK this is the standard way to do forward proxying. i.e. there is a (plain) forwarded connection established allowing the client to reach the desired server, over which TLS is established end-to-end between the client and server. There would have to be multiple handshakes otherwise. I don't think this is well supported in proxy servers, but I could be wrong.
