### ISSUE TITLE
Using nginx Upstream

### ISSUE THREAD

**Issue by ehsan310** [ledgetech/lua-resty-http#198]
Is it possible to use upstream to connect to end point ?
I have a system that I want to connect to pool of servers and I want to use upstream that I want to use weight and health check on top of this feature.

```
upstream app-servers {
    server 1.1.1.1;
}

local http = require "resty.http"
local httpc = http.new()
local res, err = httpc:request_uri("http://app-servers" .. ngx.var.request_uri, {
method = "GET",
headers = {
            ["Authorization"] = ngx.var.http_authorization,
            ["Host"] = ngx.var.host,
            ["X-Forwarded-For"] = ngx.var.remote_addr,
            ["X-Real-IP"] = ngx.var.remote_addr,
        },
keepalive_timeout = 60,
keepalive_pool = 10
})
```

**Comment by dustinbarnes** [comment]
@ehsan310 did you ever find a satisfactory answer for this?

**Comment by ehsan310** [comment]
@dustinbarnes No not really , I'm still interested in this question.

**Comment by defusevenue** [comment]
You can use other openresty libraries to achieve this. I would suggest looking at the one I've linked below. It allows you to access your upstream servers in lua, specified in your nginx config, while still utilizing the health and weight options.

Upstream Module: https://github.com/openresty/lua-upstream-nginx-module

**Comment by dustinbarnes** [comment]
That's the solution track I'm pursuing, but it's not quite what I'm asking. I basically want to have a portion of lua code self-configure based on configuration fetched from an upstream.
This is possible in the context of a request, because we can just perform a subrequest and use the built-in `ngx.location.capture` to get the body. However, during the startup phase (`init_worker_by_lua*`, and `ngx.timer.at` deferred work), we can't perform sub-requests (as there is no request). 

The only way I've found thusfar is to inspect the upstreams and iterate through the primary peers myself.  I've grabbed some code from the healthcheck module you linked, for processing the peers (getting valid host names/ips) and trying each one in succession using this lib. It's a bit janky, but I think it works. But maybe this is just my special case :)

**Comment by hamishforbes** [comment]
This project is unlikely to ever support upstream functionality, however [lua-resty-upstream](https://github.com/hamishforbes/lua-resty-upstream) can provide pure Lua upstreams and healthchecking if you the nginx module doesn't meet your needs
