### ISSUE TITLE
Connection Pool not working and not reused !

### ISSUE THREAD

**Issue by taotao2014** [ledgetech/lua-resty-http#214]
https://github.com/ledgetech/lua-resty-http/issues/160

The problem is the same.....

Connections are not reused, the number of connections increases

version 0.12 or 0.14

local function query_from_server(url)
    local http = require "resty.http"
    local httpc = http.new()
    httpc:set_timeout(3000)
    local res, err = httpc:request_uri(url, {
        version = 1.1,
        method = "GET",
       headers = {
            ["Connection"] = "Keep-Alive",
            ["Host"] = "test.domain.com"
        },
        keepalive = true,
        keepalive_pool = 20,
        keepalive_timeout = 60000
    })
   ---- httpc:set_keepalive(100,3600)
  local times, err = httpc:get_reused_times() -- [2] closed
    return res, err
end

**Comment by taotao2014** [comment]
@agentzh @pintsized

**Comment by pintsized** [comment]
Please provide a minimal configuration demonstrating the problem you're having if you expect any assistance. Simply reporting "not working" is not very helpful.

Please also note that the `request_uri` interface manages the connection and keepalive / close for you, and so testing the connection either side of this isn't going to do what you think. Be sure to use the `request` interface for more control.

As noted in #160, these tests show the current expected behaviour. They might help you understand what's going on: https://github.com/ledgetech/lua-resty-http/blob/master/t/07-keepalive.t

**Comment by taotao2014** [comment]
Have been edited

**Comment by pintsized** [comment]
What do the response headers look like? Is there a `Connection: close` in there by any chance? Does your url point to a HTTP 1.0 server (where keepalive is not possible)?

Again, I would recommend using the main generic `request` interface (instead of the `request_uri` helper), even just to see what's going on. Use the generic interface, and call `set_keepalive` yourself, and be sure to inspect the return code. As noted in the docs, you will get a positive return code if nothing bad happened, but you will get `2` instead of `1` if the connection *must* be closed (because the server said so).

If you get `nil` back for `set_keepalive`, be sure to inspect the error.

**Comment by taotao2014** [comment]
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v2.2.3.BUILD-SNAPSHOT)

{
    body = "message",
    reason = "",
    has_body = true,
    headers = {
      ["Content-Length"] = "14",
      ["Content-Type"] = "application/json",
      Date = "Thu, 11 Jun 2020 23:26:11 GMT",
      Connection = "keep-alive",
      ["Keep-Alive"] = "timeout=60"
    },
    read_body = "function: 0x41a44858",
    body_reader = "function: 0x40375108",
    status = 200,
    read_trailers = "function: 0x41a448c0"
  }

httpc:get_reused_times()--return dump "[2] = "closed""

**Comment by taotao2014** [comment]
modify httpc:request_uri to httpc:request 

local function query_from_server(path, conf)
    local httpc = http:new()
    httpc:connect("10.129.171.195",8000)
    httpc:set_timeout(conf.connect_timeout)
    local res, err = httpc:request {
        version = 1.1,
        path = "/" .. path,
        method = "GET",
         headers = {
            ["Connection"] = "Keep-Alive"
        },
    }
     local data = res:read_body()
     dump(httpc:get_reused_times())----------------return 0 
    local ok, err = httpc:set_keepalive(100,3600)
    if not ok then
        ngx.log(ngx.ERR, "could not keepalive connection: ", err)
        return nil, err
    end
    dump(httpc:get_reused_times())----------------[2] = "closed"
    return data , err
end


return :

{
    body_reader = "function: 0x414e20d0",
    reason = "",
    read_body = "function: 0x40fe86a8",
    has_body = true,
    headers = {
      ["Content-Length"] = "14",
      ["Content-Type"] = "application/json",
      Date = "Fri, 12 Jun 2020 02:10:54 GMT",
      Connection = "keep-alive",
      ["Keep-Alive"] = "timeout=60"
    },
    status = 200,
    read_trailers = "function: 0x40fe8710"
  }

**Comment by taotao2014** [comment]
resty http (10.129.8.157 )    -- >  mvc site (10.129.171.195):

  Concurrent request for the first time

  keepalive: 16

 
  TCP    10.129.171.195:8000    10.129.8.157:62807     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:62861     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:62989     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63055     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63093     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63099     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63101     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63135     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63207     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63319     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63351     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63365     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63369     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63371     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63375     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:63377     ESTABLISHED     22400

 Wait 10 seconds...

 Concurrent request for the second  time

  keepalive: 16

  TCP    10.129.171.195:8000    10.129.8.157:9440      ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:9674      ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10550     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10834     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10858     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10896     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10904     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10912     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10916     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10920     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10946     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10952     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10966     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10970     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10972     ESTABLISHED     22400
  TCP    10.129.171.195:8000    10.129.8.157:10974     ESTABLISHED     22400

 but,  connections are not reuse..

**Comment by taotao2014** [comment]
Connection reuse only during use, is this normal behavior of http.resty?

dump(httpc:get_reused_times()) result:


2020/06/12 16:46:45 [error] 16837#0: *162519 [kong] handler.lua:6 {
  17
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162507 [kong] handler.lua:6 {
  5
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16836#0: *162551 [kong] handler.lua:6 {
  0
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16838#0: *162529 [kong] handler.lua:6 {
  16
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16837#0: *162540 [kong] handler.lua:6 {
  17
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162509 [kong] handler.lua:6 {
  5
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16836#0: *162521 [kong] handler.lua:6 {
  0
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16838#0: *162531 [kong] handler.lua:6 {
  16
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162504 [kong] handler.lua:6 {
  5
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16836#0: *162556 [kong] handler.lua:6 {
  0
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162512 [kong] handler.lua:6 {
  5
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16836#0: *162553 [kong] handler.lua:6 {
  0
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162508 [kong] handler.lua:6 {
  5
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162501 [kong] handler.lua:6 {
  5
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162514 [kong] handler.lua:6 [example-static-file-concat/...] {
  9
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16837#0: *162541 [kong] handler.lua:6 [example-static-file-concat/...] {
  20
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16836#0: *162557 [kong] handler.lua:6 [example-static-file-concat/...] {
  25
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16837#0: *162518 [kong] handler.lua:6 {
  20
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16836#0: *162559 [kong] handler.lua:6 {
  25
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16837#0: *162517 [kong] handler.lua:6 {
  20
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16836#0: *162552 [kong] handler.lua:6 {
  25
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162511 [kong] handler.lua:6 [example-static-file-concat/...] {
  0
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16836#0: *162554 [kong] handler.lua:6 {
  25
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16837#0: *162516 [kong] handler.lua:6 {
  20
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162510 [kong] handler.lua:6 {
  0
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16836#0: *162525 [kong] handler.lua:6 [example-static-file-concat/...] {
  3
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162513 [kong] handler.lua:6 {
  0
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162505 [kong] handler.lua:6 [example-static-file-concat/...] {
  7
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16838#0: *162535 [kong] handler.lua:6 [example-static-file-concat/...] {
  29
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16838#0: *162532 [kong] handler.lua:6 {
  29
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16838#0: *162526 [kong] handler.lua:6 {
  29
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16837#0: *162520 [kong] handler.lua:6 [example-static-file-concat/...] {
  18
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16838#0: *162533 [kong] handler.lua:6 {
  29
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16837#0: *162519 [kong] handler.lua:6 {
  18
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16838#0: *162534 [kong] handler.lua:6 {
  29
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16838#0: *162536 [kong] handler.lua:6 {
  [2] = "closed"
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16836#0: *162558 [kong] handler.lua:6 [example-static-file-concat/...] {
  19
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16835#0: *162503 [kong] handler.lua:6 [example-static-file-concat/...] {
  13
}, client: 10.129.7.155, server: kong, request: "GET /concat/... HTTP/1.1", host: "stnew.example.com"
2020/06/12 16:46:45 [error] 16837#0: *162517 [kong] handler.lua:6 [example-static-file-concat/...] {

**Comment by pintsized** [comment]
See here for notes on how to interpret `get_reused_times`: https://github.com/openresty/lua-nginx-module/#tcpsockgetreusedtimes

And here for details on establishing a connection pool with a given size: https://github.com/openresty/lua-nginx-module/#tcpsockconnect. These behaviours in OpenResty have changed, in fact, our `lua-resty-http` docs seem out of date compared to this, so please be sure to understand the `tcpsock:connect` behaviour from the the official OpenResty documentation.

With regards to `lua-resty-http` behaviour, if using the generic interface then you have the most control and the arguments you provide will map straight onto the underlying `cosocket` equivalents. The only "magic" happens if the response indicates the connection should be closed. In which case we allow you to call `set_keepalive` safely and just call `close` instead for you - and we return a different code to let you know this happened (which you are not checking in your example code).

So again, please read these docs to understand the return code you expect from `set_keepalive`: https://github.com/ledgetech/lua-resty-http#set_keepalive

**Comment by KongGuide** [comment]
Thanks a lot, the problem is solved。

http.resty 0.12--.>ngx_lua-0.10.13
http.resty 0.14--.>ngx_lua-0.10.14


-----------------------------------------------
local function query_from_server(url)
local http = require "resty.http"
local httpc = http.new()
httpc:set_timeout(3000)
local res, err = httpc:request_uri(url, {
version = 1.1,
method = "GET",
headers = {
["Connection"] = "Keep-Alive",
["Host"] = "test.domain.com"
},
keepalive = true,
keepalive_pool = 1,
keepalive_timeout = 60000
})
-----------------------------

Use http.resty 0.14, connection is not reused
Use http.resty 0.12, connection is reused

**Comment by taotao2014** [comment]
Thanks a lot, the problem is solved。

http.resty 0.12--.>ngx_lua-0.10.13
http.resty 0.14--.>ngx_lua-0.10.14

local function query_from_server(url)
local http = require "resty.http"
local httpc = http.new()
httpc:set_timeout(3000)
local res, err = httpc:request_uri(url, {
version = 1.1,
method = "GET",
headers = {
["Connection"] = "Keep-Alive",
["Host"] = "test.domain.com"
},
keepalive = true,
keepalive_pool = 1,
keepalive_timeout = 60000
})
Use http.resty 0.14, connection is not reused
Use http.resty 0.12, connection is reused

**Comment by leland17** [comment]
> 

why high version http.resty do not reuse Connection? 

in my case，the version of ngx_lua is 0.10.20， how should i do？

**Comment by pintsized** [comment]
Connection reuse does work. It works for probably millions of requests-per-second in `lua-resty-http` installations all over the world. If it does not work for you, it is almost certainly not because of a bug in this library.

There are many reasons why a specific connection is not reused. These reasons include; the HTTP semantics of your particular request, the server configuration, the keepalive pool configuration in `ngx_lua`, any in-flight errors, bad response content length, as well as potential coding errors on your side (for example, calling `set_keepalive()` in the wrong place).

If you are not fully familiar the `ngx_lua` keepalive pool system, I would suggest reading the documentation there first.

If you are still confused, please open a new issue here with a complete, minimal reproducible configuration example, and maybe someone can help you figure it out.
