### ISSUE TITLE
client gets closed when passed to ngx.timer.at

### ISSUE THREAD

**Issue by kollol-chowdhury-incontact** [ledgetech/lua-resty-http#278]
I create an http client and when i send the client to ngx.timer.at and try to use there,it always gives me connection closed even if i set keepalive value to a large value.
Is it possible to share an http client with ngx.timer.at

**Comment by pintsized** [comment]
A `lua-resty-http` client is just a wrapper around a `cosocket`, which has a lifetime attached to the request. As the documentation clearly points out, you cannot share a `cosocket` with a timer thread: https://github.com/openresty/lua-nginx-module/#ngxtimerat

You probably also need to read the documentation around `setkeepalive` as I suspect that it does not do what you might think it does (it closes the connection, placing it on the keepalive pool for a subsequent connection).

However, you can *create* a `lua-resty-http` client *inside* a timer light thread. You obviously won't be able to do much with the response - remember that the parent thread (i.e. your request) has a different lifetime to the timer thread.

**Comment by kollol-chowdhury-incontact** [comment]
So every call inside the timer thread should create a new http client?isn't that a bit expensive operation because my problem requires 100s of call per second, which means 100s of new http client creation.

**Comment by pintsized** [comment]
What makes you think it's expensive? The client is just a Lua table, and so calling `new()` is cheap. The expensive part is making an actual TCP connection, which is why we have a keepalive pool. In healthy scenarios, most of your calls to `connect` simply pull a previously established connection from the pool.

I'm not sure how reliable things will be when trying to create 100s of HTTP requests per second inside a timer thread, but then I don't know your use case. Just be aware that there are limits to the number of pending and active timers you can have, and that each timer is actually a "fake request" thread. Nginx reclaims memory at the end of the request, assuming it to be relatively short lived. So be aware that you can exhaust system resources with this method. Again, this is covered in the `lua-nginx-module` documentation.
