### ISSUE TITLE
Downloading a 200 megabyte file causes nginx work exited

### ISSUE THREAD

**Issue by startcodeing** [ledgetech/lua-resty-http#283]
i use openresty 1.19.9.1 on windows,I want to use the proxy cache mechanism to cache files from the upgrade source，here is my minimal code and nginx config

lua code:
`local http = require "resty.http"

local function cacheFileWithProxyCacheFromUpgradeSource(){
local fileUriList = {"/xxxx/file1","/xxxx/file2","/xxxx/file3",...}
for _,v in pairs(fileUriList) do
    local cacheFileRequestUri = "http://127.0.0.1:36000/" .. v
    local httpc = http.new();
    local res,err = httpc:request_uri(cacheFileRequestUri,{
    method = "GET",
    headers = {
         ["Host"] = xxx,
    }
})
if res.status == 200 then
    ngx.log(ngx.INFO,"file cache success")
end
then
}`
nginx config:
server {
listen 36000;
server_name xxx;
proxy_cache_path download/proxyCache levels=1:2 keys_zone=proxyCacheZone:500m inactive=30d max_size=100g use_temp_path=off;

location / {
     proxy_cache proxyCacheZone;
    proxy_cache_key $host$uri$is_args$args;
    proxy_cache_valid  200 206 304 301 302 30d;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_ignore_headers "Cache-Control" "Expires" "Set-Cookie";
    add_header X-Cache $upstream_cache_status;
    proxy_set_header Connection keep-alive;
    proxy_pass http://upgradeSourceIp:upgradeSourcePort;
}
}

it's work well when file is only a few megabytes，But when I cache a file with more than 200 megabytes,i got errr as below:

2022/12/12 16:05:59 [notice] 17336#31320: worker process 31036 exited with code E24C4A04
2022/12/12 16:05:59 [notice] 17336#31320: start worker process 30828

The strange thing is that everything works fine under the linux system. I didn't find any related issue discussion in the issue list of github and google，how to solve it? Can someone offer some ideas for a solution?

**Comment by pintsized** [comment]
You're going to want to use the streaming interface instead of the "single-shot" interface: https://github.com/ledgetech/lua-resty-http#usage

To be clear (as the docs aren't great), `request_uri` is intended for relatively small and **complete** requests, where you want the whole body in Lua land. For example, an API request which returns some JSON that you wish to parse. If you point this at a 200MB file, well then you'll end up with a 200MB string in Lua memory, and a very unhappy nginx worker.

The streaming API on the other hand performs the request, reads the status and headers, and **leaves the body on the wire**. You must then read it (in chunks), and do something with them one at a time. That is, don't concatenate them into a large body, but send them downstream to the client or push them into some other end point, etc.

In your case I think you can just discard them as you seem to simply be priming a cache? If that's the case, just read the response one chunk at a time and do nothing with it. But you must read the whole thing, otherwise it'll just sit there on the wire, your cache won't get primed and you won't be able to reuse the connection.

**Comment by startcodeing** [comment]
> 

Thank you for your reply. After creating this issue, I read the documentation of lua-resty-http in detail. just like what you said, I realized that the way I used it was wrong, so I tried to use the Streamed requests model, and finally the problem was solved.
