### ISSUE TITLE
Maybe BUG？body_reader 读取字节 小于5时与 大于5时响应header不一致

### ISSUE THREAD

**Issue by frostnotfall** [ledgetech/lua-resty-http#293]
Very strange question:  

When the size of body_reader() is >= 5, there are duplicate header keys in the response headers, if you modify header at this time, only one of duplicated header key would take effect.
![image](https://user-images.githubusercontent.com/38377709/227884373-eb702e4e-8ca2-4f3c-8483-d2f437a47e95.png)

When the body_reader is < 5, there are basically no duplicate header keys in the response header, except for header["Connection"].
![image](https://user-images.githubusercontent.com/38377709/227886526-03929afd-ac34-4856-8c7e-8c9ab1c59b5d.png)

Update:
Upstream server problem, close this issue

**Comment by pintsized** [comment]
Please, as a courtesy to others, take the time to translate your questions into English.

If you think there is a bug, please submit a minimal yet **complete** example which demonstrates the issue. Code snippets are not good enough, it needs to be a complete example which other people can run, in order to replicate your problem.

If I had to guess, perhaps your `res` variable is global by accident?
