### ISSUE TITLE
Install fails with Version 0.17.2-0

### ISSUE THREAD

**Issue by jonaspu** [ledgetech/lua-resty-http#310]
### Docker build fails when installing new Version 0.17.2-0.

**Base Image:** openresty/openresty:1.25.3.1-2-jammy

**Command:** `RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-http 0.17.2-0`

**Result:**
```
 [3/6] RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-http 0.17.2-0:
#0 2.631 Installing https://luarocks.org/lua-resty-http-0.17.2-0.rockspec
#0 3.800 
#0 3.800 Error: 'git' program not found. Make sure Git is installed and is available in your PATH (or you may want to edit the 'variables.GIT' value in file '/usr/local/openresty/luajit/etc/luarocks/config-5.1.lua')
```

This worked previously with Version 0.17.1-0.

We've discovered this because we install `lua-resty-openidc`, which has a dependency to `lua-resty-http`.

**Workaround for now:** Installing the older Version explicitly: `/usr/local/openresty/luajit/bin/luarocks install lua-resty-http 0.17.2-0`

**Comment by pintsized** [comment]
The rockspec hasn't changed other than the tag. I'm not sure how you'd expect it to work without `git` installed though?

**Comment by jonaspu** [comment]
I'm aware, I've checked the diff and found nothing that could cause this. Still interesting that it seems to work perfectly fine with the previous version.

Here is a minimal docker file that works:
```
FROM openresty/openresty:1.21.4.3-bionic

EXPOSE 80

RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-http 0.17.1-0
```

And one that doesnt work with the new version:
```
FROM openresty/openresty:1.21.4.3-bionic

EXPOSE 80

RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-http 0.17.2-0
```

**Comment by renedupont** [comment]
I am facing the same issue. Yesterday it worked, today not anymore because of the error above. 
I have no prior experience with lua etc. but when trying to find the issue I read:
_luarocks uses git to download and install packages from source when they are not available as pre-compiled binaries._
In case that is true, might it be that the pre-compiled binary is not available at luarocks packet manager or something like this?

Otherwise I have no idea why it does not work anymore, yesterday I also had no git installed in the container that runs it and it worked.

As a temp workaround I'm just doing this:
```
RUN dnf install -y git
RUN luarocks install lua-resty-openidc
```

**Comment by pintsized** [comment]
Can you retry now? The package didn't get uploaded.

**Comment by jonaspu** [comment]
Seems to be working now, thanks for the quick fix :)

**Comment by renedupont** [comment]
for me as well, thanks!
